# Generated by Django 5.2.7 on 2025-10-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('nama_perusahaan', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('jurusan', models.CharField(choices=[('agro', 'Agribisnis Pembibitan Tanaman'), ('pm', 'Pemasaran'), ('rpl', 'Rekayasa Perangkat Lunak'), ('tki', 'Kimia Industri'), ('tei', 'Teknik Elektronika Industri'), ('tkj', 'Teknik Komputer dan Jaringan')], max_length=50)),
                ('alamat', models.TextField()),
                ('deskripsi', models.TextField()),
                ('foto_perusahaan', models.ImageField(blank=True, null=True, upload_to='perusahaan_foto/')),
                ('foto_guru', models.ImageField(blank=True, null=True, upload_to='guru_foto/')),
                ('foto_siswa', models.ImageField(blank=True, null=True, upload_to='siswa_foto/')),
            ],
        ),
    ]
