# Generated by Django 5.2.7 on 2025-10-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perusahaan',
            name='foto_guru',
        ),
        migrations.RemoveField(
            model_name='perusahaan',
            name='foto_siswa',
        ),
    ]
