# Generated by Django 5.2.7 on 2025-10-29 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('dipindahkan', 'Dipindahkan')], max_length=20)),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(blank=True, limit_choices_to={'role': 'guru'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_siswa_g', to=settings.AUTH_USER_MODEL, to_field='nip')),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.perusahaan')),
                ('siswa', models.ForeignKey(limit_choices_to={'role': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_siswa_s', to=settings.AUTH_USER_MODEL, to_field='nisn')),
            ],
        ),
        migrations.CreateModel(
            name='PendaftaranPKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('alasan', models.TextField()),
                ('cv', models.FileField(upload_to='cv_siswa/')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('dipindahkan', 'Dipindahkan')], default='menunggu', max_length=20)),
                ('notifikasi', models.TextField(blank=True, null=True)),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.perusahaan')),
                ('siswa', models.ForeignKey(limit_choices_to={'role': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran_pkl', to=settings.AUTH_USER_MODEL, to_field='nisn')),
            ],
        ),
    ]
