# Generated by Django 5.2.6 on 2025-11-01 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_perusahaan_foto_guru_and_more'),
        ('siswa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxsiswa',
            name='perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_perusahaan_siswa', to='admin_app.perusahaan'),
        ),
        migrations.AlterField(
            model_name='pendaftaranpkl',
            name='perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran_perusahaan_siswa', to='admin_app.perusahaan'),
        ),
        migrations.AlterField(
            model_name='pendaftaranpkl',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('wawancara', 'Wawancara'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('dipindahkan', 'Dipindahkan')], default='menunggu', max_length=20),
        ),
    ]
