# Generated by Django 5.2.6 on 2025-11-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa_app', '0002_alter_inboxsiswa_perusahaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaranpkl',
            name='tanggal_wawancara',
            field=models.DateTimeField(blank=True, help_text='Tanggal wawancara untuk siswa.', null=True),
        ),
        migrations.AlterField(
            model_name='inboxsiswa',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('wawancara', 'Wawancara'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('dipindahkan', 'Dipindahkan')], max_length=20),
        ),
    ]
