# Generated by Django 5.2.7 on 2025-11-02 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa_app', '0003_pendaftaranpkl_tanggal_wawancara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaranpkl',
            name='tanggal_daftar',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 2, 9, 30), help_text='Tanggal pendaftaran siswa.'),
            preserve_default=False,
        ),
    ]
