# Generated by Django 5.2.7 on 2025-11-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa_app', '0004_pendaftaranpkl_tanggal_daftar'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxsiswa',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
