# Generated by Django 5.2.7 on 2025-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa_app', '0005_inboxsiswa_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboxsiswa',
            options={'ordering': ['-tanggal_kirim']},
        ),
        migrations.AlterField(
            model_name='inboxsiswa',
            name='is_read',
            field=models.BooleanField(default=False, help_text='True jika siswa sudah membaca pesan.'),
        ),
        migrations.AlterField(
            model_name='inboxsiswa',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('wawancara', 'Wawancara'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('dipindahkan', 'Dipindahkan')], default='menunggu', max_length=20),
        ),
    ]
