# Generated by Django 5.2.7 on 2025-11-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa_app', '0006_alter_inboxsiswa_options_alter_inboxsiswa_is_read_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboxsiswa',
            options={},
        ),
        migrations.AlterField(
            model_name='inboxsiswa',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inboxsiswa',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('wawancara', 'Wawancara'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('dipindahkan', 'Dipindahkan')], max_length=20),
        ),
    ]
