# Generated by Django 5.2.7 on 2025-11-12 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_perusahaan_foto_guru_and_more'),
        ('siswa_app', '0007_alter_inboxsiswa_options_alter_inboxsiswa_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboxsiswa',
            options={'ordering': ['-tanggal_kirim']},
        ),
        migrations.AlterField(
            model_name='inboxsiswa',
            name='guru',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'guru'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_siswa_guru', to=settings.AUTH_USER_MODEL, to_field='nip'),
        ),
        migrations.AlterField(
            model_name='inboxsiswa',
            name='is_read',
            field=models.BooleanField(default=False, help_text='True jika siswa sudah membaca pesan.'),
        ),
        migrations.AlterField(
            model_name='inboxsiswa',
            name='perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_siswa_perusahaan', to='admin_app.perusahaan'),
        ),
        migrations.AlterField(
            model_name='inboxsiswa',
            name='siswa',
            field=models.ForeignKey(limit_choices_to={'role': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_siswa', to=settings.AUTH_USER_MODEL, to_field='nisn'),
        ),
        migrations.AlterField(
            model_name='inboxsiswa',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('wawancara', 'Wawancara'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('dipindahkan', 'Dipindahkan')], default='menunggu', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendaftaranpkl',
            name='tanggal_daftar',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pendaftaranpkl',
            name='tanggal_wawancara',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
