# Generated by Django 5.2.7 on 2025-11-12 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_perusahaan_foto_guru_and_more'),
        ('siswa_app', '0008_alter_inboxsiswa_options_alter_inboxsiswa_guru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxsiswa',
            name='perusahaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_siswa_perusahaan', to='admin_app.perusahaan'),
        ),
    ]
