# Generated by Django 5.2.7 on 2025-10-29 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('dipindahkan', 'Dipindahkan')], max_length=20)),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(limit_choices_to={'role': 'guru'}, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_guru', to=settings.AUTH_USER_MODEL, to_field='nip')),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.perusahaan')),
                ('siswa', models.ForeignKey(limit_choices_to={'role': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_siswa_from_guru', to=settings.AUTH_USER_MODEL, to_field='nisn')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalWawancara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_wawancara', models.DateTimeField()),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('dipindahkan', 'Dipindahkan')], max_length=20)),
                ('guru', models.ForeignKey(limit_choices_to={'role': 'guru'}, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_guru', to=settings.AUTH_USER_MODEL, to_field='nip')),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.perusahaan')),
                ('siswa', models.ForeignKey(limit_choices_to={'role': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_siswa', to=settings.AUTH_USER_MODEL, to_field='nisn')),
            ],
        ),
    ]
