# Generated by Django 5.2.6 on 2025-11-01 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_perusahaan_foto_guru_and_more'),
        ('guru_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxguru',
            name='tanggal_wawancara',
            field=models.DateTimeField(blank=True, help_text='Tanggal wawancara jika sudah dijadwalkan.', null=True),
        ),
        migrations.AlterField(
            model_name='inboxguru',
            name='perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_perusahaan_guru', to='admin_app.perusahaan'),
        ),
        migrations.AlterField(
            model_name='inboxguru',
            name='pesan',
            field=models.TextField(help_text='Pesan dari guru ke siswa (misalnya: jadwal wawancara, hasil seleksi, dll.)'),
        ),
        migrations.AlterField(
            model_name='inboxguru',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('wawancara', 'Wawancara'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('dipindahkan', 'Dipindahkan')], default='menunggu', max_length=20),
        ),
        migrations.DeleteModel(
            name='JadwalWawancara',
        ),
    ]
