# Generated by Django 5.2.6 on 2025-11-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru_app', '0002_inboxguru_tanggal_wawancara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxguru',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
