# Generated by Django 5.2.7 on 2025-11-02 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_perusahaan_foto_guru_and_more'),
        ('guru_app', '0003_inboxguru_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxguru',
            name='alasan_pemindahan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboxguru',
            name='perusahaan_baru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_perusahaan_baru_guru', to='admin_app.perusahaan'),
        ),
        migrations.AddField(
            model_name='inboxguru',
            name='perusahaan_lama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_perusahaan_lama_guru', to='admin_app.perusahaan'),
        ),
        migrations.AlterField(
            model_name='inboxguru',
            name='pesan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inboxguru',
            name='tanggal_wawancara',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
