# Generated by Django 5.2.7 on 2025-11-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru_app', '0004_inboxguru_alasan_pemindahan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxguru',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
