# Generated by Django 5.2.7 on 2025-11-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru_app', '0005_inboxguru_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxguru',
            name='dikirim_oleh',
            field=models.CharField(choices=[('siswa', 'Siswa'), ('guru', 'Guru'), ('system', 'Sistem')], default='siswa', help_text='Menandakan siapa pengirim pesan (siswa/guru/sistem)', max_length=10),
        ),
    ]
