# Generated by Django 5.2.7 on 2025-11-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru_app', '0006_inboxguru_dikirim_oleh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxguru',
            name='dikirim_oleh',
            field=models.CharField(choices=[('siswa', 'Siswa'), ('guru', 'Guru'), ('system', 'Sistem')], default='guru', help_text='Menandakan siapa pengirim pesan (siswa/guru/sistem)', max_length=10),
        ),
    ]
