# Generated by Django 5.2.7 on 2025-10-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_guru',
            field=models.ImageField(blank=True, null=True, upload_to='guru_foto/'),
        ),
    ]
