# Generated by Django 5.2.7 on 2025-10-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customuser_foto_guru'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_siswa',
            field=models.ImageField(blank=True, null=True, upload_to='siswa_foto/'),
        ),
    ]
